kind: pipeline
name: стадия1
group: first

steps:
- name: build
  image: node:11.7.0-slim
  commands:
  - npm install
  - npm test

---

kind: pipeline
name: стадия2
group: second

steps:
- name: step1
  image: node:11.7.0-slim
  commands:
  - echo -e "\e[31mHello World\e[0m"

