kind: pipeline
name: стадия1
group: first

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

---  

kind: pipeline
name: стадия2
group: second

steps:
- name: step1
  image: node
  commands:
  - npm install
  - npm test

