pipeline:
  frontend_A:
    image: node
    commands:
    - npm install
    - npm run test:unit
    
  frontend_B:
    image: node
    group: installation
    commands:
    - npm install
    - npm run test:unit    
    
  frontend_C:
    image: node
    group: installation
    commands:
    - npm install
    - npm run test:unit      
    
services:
  database:
    image: mysql    
