kind: pipeline
name: frontend
group: first

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
- name: build2
  image: node
  commands:
  - npm install
  - npm test
  
- name: build3
  image: node
  commands:
  - npm install
  - npm test  
  
---  
kind: pipeline
name: iOS
group: first

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test  
  
steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test  

---
kind: pipeline
name: backend1

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

services:
- name: redis
  image: redis
  
---
kind: pipeline
name: backend2

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend3

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend4

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend5

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend6

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend7

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend8

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend9

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend10

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
---
kind: pipeline
name: backend11

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test  
