kind: pipeline
name: frontend
group: first

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test
  
- name: build2
  image: node
  commands:
  - npm install
  - npm test
  
- name: build3
  image: node
  commands:
  - npm install
  - npm test  
  
---  
kind: pipeline
name: iOS
group: first

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test  
  
steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test  

---
kind: pipeline
name: backend

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

services:
- name: redis
  image: redis
