kind: pipeline
name: frontend

steps:
- name: very-very-very-very-very-very-very-very-very-long-step-name
  image: node
  commands:
  - npm install
  - npm test
  - echo 1
  - sleep 1
  - echo 2
  - sleep 1
  - echo 3
  - sleep 1
  - echo 4
  - sleep 1
  - echo 5
  - sleep 1
  - echo 6
  - sleep 1
  - echo 7
  - sleep 1
  - echo 8
  - sleep 1
  - echo 9
  - sleep 1
  - echo 10
  - sleep 1
  - echo 11
  - sleep 1
  - echo 12
  - sleep 1
  - echo 13
  - sleep 1
  - echo 14
  - sleep 1
  - echo 15
  - sleep 1
  - echo 16
  - sleep 1
  - echo 17
  - sleep 1
  - echo 18
  - sleep 1
  - echo 19
  - sleep 1
  - echo 20
  - sleep 1
  - echo 21
  - sleep 1
  - echo 22
  - sleep 1
  - echo 23
  - sleep 1
  - echo 24
  - sleep 1
  - echo 25
  - sleep 1
  - echo 26
  - sleep 1
  - echo 27
  - sleep 1
  - echo 28
  - sleep 1
  - echo 29
  - sleep 1
  - echo 30
  - sleep 1
  - echo 31
  - sleep 1
  - echo 32
  - sleep 1
  - echo 33
  - sleep 1
  - echo 34
  - sleep 1
  - echo 35
  - sleep 1
  - echo 36
  - sleep 1
  - echo 37
  - sleep 1
  - echo 38
  - sleep 1
  - echo 39
  - sleep 1
  - echo 40
  - sleep 1
  - echo 41
  - sleep 1
  - echo 42
  - sleep 1
  - echo 43
  - sleep 1
  - echo 44
  - sleep 1
  - echo 45
  - sleep 1
  - echo 46
  - sleep 1
  - echo 47
  - sleep 1
  - echo 48
  - sleep 1
  - echo 49
  - sleep 1
  - echo 50
  - sleep 1
  - echo 51
  - sleep 1
  - echo 52
  - sleep 1
  - echo 53
  - sleep 1
  - echo 54
  - sleep 1
  - echo 55
  - sleep 1
  - echo 56
  - sleep 1
  - echo 57
  - sleep 1
  - echo 58
  - sleep 1
  - echo 59
  - sleep 1
  - echo 60
  - sleep 1
  - echo 61
  - sleep 1
  - echo 62
  - sleep 1
  - echo 63
  - sleep 1
  - echo 64
  - sleep 1
  - echo 65
  - sleep 1
  - echo 66
  - sleep 1
  - echo 67
  - sleep 1
  - echo 68
  - sleep 1
  - echo 69
  - sleep 1
  - echo 70
  - sleep 1
  - echo 71
  - sleep 1
  - echo 72
  - sleep 1
  - echo 73
  - sleep 1
  - echo 74
  - sleep 1
  - echo 75
  - sleep 1
  - echo 76
  - sleep 1
  - echo 77
  - sleep 1
  - echo 78
  - sleep 1
  - echo 79
  - sleep 1
  - echo 80
  - sleep 1
  - echo 81
  - sleep 1
  - echo 82
  - sleep 1
  - echo 83
  - sleep 1
  - echo 84
  - sleep 1
  - echo 85
  - sleep 1
  - echo 86
  - sleep 1
  - echo 87
  - sleep 1
  - echo 88
  - sleep 1
  - echo 89
  - sleep 1
  - echo 90
  - sleep 1
  - echo 91
  - sleep 1
  - echo 92
  - sleep 1
  - echo 93
  - sleep 1
  - echo 94
  - sleep 1
  - echo 95
  - sleep 1
  - echo 96
  - sleep 1
  - echo 97
  - sleep 1
  - echo 98
  - sleep 1
  - echo 99
  - sleep 1
  - echo 100
  - sleep 1
