kind: pipeline
name: frontend

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

---
kind: pipeline
name: backend

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm test

services:
- name: redis
  image: redis
